/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import OBJECTS.CPU;

/**
 *
 * @author camilafermosoiglesias
 */
public class CPUDisplay extends javax.swing.JFrame {

    /**
     * Creates new form CPUDisplay
     */

    private CPU cpu;

    public CPUDisplay(CPU cpu) {
        initComponents();
        this.cpu = cpu;
        // actualizarInterfaz();
        
        // Tamaño del CPU Display
        this.setMinimumSize(new java.awt.Dimension(250, 200));
        this.setPreferredSize(new java.awt.Dimension(250, 200));
        this.setMaximumSize(new java.awt.Dimension(300, 200));
    }

    private CPUDisplay() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    // Para actualizar la informacion y cada valor de la CPU en la interfaz
    public void updateCPUDisplay() {
        //Actualizar el numero de CPU (1,2,3)
        CPUIDVAR.setText(String.valueOf(cpu.getCpuId()));
        
        // Actualizer los valores del proceso en el CPU display
        
        ProcesoVAR.setText(cpu.getCurrentProcess() != null ? cpu.getCurrentProcess().getName() : "Proceso");
        IDVAR.setText(cpu.getCurrentProcess() != null ? String.valueOf(cpu.getCurrentProcess().getProcessID()) : "No Disponible" );
        EstadoVAR.setText(cpu.getCurrentProcess() != null ? String.valueOf(cpu.getCurrentProcess().getState()) : "No Disponible");
        PCEstadoVAR.setText(cpu.getCurrentProcess() != null ? String.valueOf(cpu.getCurrentProcess().getProgramCounter()) : "No Disponible");
        EstadoMARVAR.setText(cpu.getCurrentProcess() != null ? String.valueOf(cpu.getCurrentProcess().getMemoryAddressRegister()) : "No Disponible");
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelCPU = new javax.swing.JLabel();
        LabelProceso = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        EstadoLabel = new javax.swing.JLabel();
        LabelPCStat = new javax.swing.JLabel();
        LabelMARStat = new javax.swing.JLabel();
        ProcesoVAR = new javax.swing.JLabel();
        IDVAR = new javax.swing.JLabel();
        EstadoVAR = new javax.swing.JLabel();
        PCEstadoVAR = new javax.swing.JLabel();
        EstadoMARVAR = new javax.swing.JLabel();
        CPUIDVAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCPU.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        LabelCPU.setText("CPU");
        jPanel1.add(LabelCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        LabelProceso.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        LabelProceso.setText("Nombre del Proceso:");
        jPanel1.add(LabelProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        IDLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        IDLabel.setText("ID:");
        jPanel1.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        EstadoLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        EstadoLabel.setText("Estado:");
        jPanel1.add(EstadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        LabelPCStat.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        LabelPCStat.setText("Estado PC:");
        jPanel1.add(LabelPCStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        LabelMARStat.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        LabelMARStat.setText("Estado MAR:");
        jPanel1.add(LabelMARStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        ProcesoVAR.setText("Proceso");
        jPanel1.add(ProcesoVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        IDVAR.setText("ID Proceso");
        jPanel1.add(IDVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        EstadoVAR.setText("Estado Proceso");
        jPanel1.add(EstadoVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        PCEstadoVAR.setText("Estado PC");
        jPanel1.add(PCEstadoVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        EstadoMARVAR.setText("Estado MAR");
        jPanel1.add(EstadoMARVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        CPUIDVAR.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        CPUIDVAR.setText("X");
        jPanel1.add(CPUIDVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPUDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPUDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPUDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPUDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPUDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPUIDVAR;
    private javax.swing.JLabel EstadoLabel;
    private javax.swing.JLabel EstadoMARVAR;
    private javax.swing.JLabel EstadoVAR;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel IDVAR;
    private javax.swing.JLabel LabelCPU;
    private javax.swing.JLabel LabelMARStat;
    private javax.swing.JLabel LabelPCStat;
    private javax.swing.JLabel LabelProceso;
    private javax.swing.JLabel PCEstadoVAR;
    private javax.swing.JLabel ProcesoVAR;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
